version: "3"

networks:
  front:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  node_1:
    build: ./
    environment:
      CURRENT_NODE_ID: "node_1"
    networks:
      front:
        ipv4_address: 172.20.0.101
  node_2:
    build: ./
    environment:
      CURRENT_NODE_ID: "node_2"
    networks:
      front:
        ipv4_address: 172.20.0.102
  node_3:
    build: ./
    environment:
      CURRENT_NODE_ID: "node_3"
    networks:
      front:
        ipv4_address: 172.20.0.103
